# This is a neoforge.mods.toml file. It contains the data relating to loading mods.
# The overall format is standard TOML format, v0.5.0.

# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory

# A version range to match for said mod loader - for regular FML @Mod it will be the FML version.
loaderVersion="${loader_version_range}" #mandatory

# The license for your mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
license="${mod_license}"

[[mods]] #mandatory
modId="${mod_id}" #mandatory
version="${mod_version}" #mandatory
displayName="${mod_name}" #mandatory
displayURL="https://www.curseforge.com/minecraft/mc-mods/the-time-vortex/files?page=1&pageSize=20"
logoFile="assets/${mod_id}/logo.png"
authors="${mod_authors}"
description='''${mod_description}'''

[[mixins]]
config="mixins.vortexmod.json"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

